In [5]:

data <- read.csv("zoo.csv")


head(data)

  animal_name hair feathers eggs milk airborne aquatic predator toothed
1 aardvark    1    0        0    1    0        0       1        1
2 antelope    1    0        0    1    0        0       0        1
3 bass        0    0        1    0    0        1       1        1
4 bear        1    0        0    1    0        0       1        1
5 boar        1    0        0    1    0        0       1        1
6 buffalo     1    0        0    1    0        0       0        1
  backbone breathes venomous fins legs tail domestic catsize class_type
1 1        1        0        0    4    0    0        1       1
2 1        1        0        0    4    1    0        1       1
3 1        0        0        1    0    1    0        0       4
4 1        1        0        0    4    0    0        1       1
5 1        1        0        0    4    1    0        1       1
6 1        1        0        0    4    1    0        1       1

In [ ]:
# Install required libraries if not already installed
if (!require("shiny")) install.packages("shiny")
if (!require("plotly")) install.packages("plotly")
if (!require("dplyr")) install.packages("dplyr")

# Load libraries
library(shiny)
library(plotly)
library(dplyr)

# Load the dataset
zoo_data <- read.csv("zoo.csv")

ui <- fluidPage(
  titlePanel("Zoo Dataset Interactive Dashboard"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Explore the Zoo dataset with interactive visualizations."),
    ),
    
    mainPanel(
      # Center the title below the dashboard of 3 visualizations
      div(style = "text-align: center; font-size: 24px; margin-bottom: 20px;", 
          h3("Interactive Zoo Dataset Visualizations")),
      
      # Wrap the visualizations in a fluidRow to display them side by side in rows of 3
      div(style = "overflow-y: scroll; max-height: 800px;",  # Scrollable area for the entire content
          fluidRow(
            column(4, plotlyOutput("class_legs_bar")),  # First visualization
            column(4, plotlyOutput("airborne_donut")),  # Second visualization
            column(4, plotlyOutput("predator_area"))  # Third visualization
          ),
          fluidRow(
            column(4, plotlyOutput("legs_bar")),  # Fourth visualization
            column(4, plotlyOutput("class_legs_heatmap")),  # Fifth visualization
            column(4, plotlyOutput("class_type_pie"))  # Sixth visualization
          )
      )
    )
  )
)


# Server logic
server <- function(input, output) {

   # 1. Bar Chart: Leg Count by Animal Class
  output$class_legs_bar <- renderPlotly({
    class_legs <- zoo_data %>%
      group_by(class_type, legs) %>%
      summarise(count = n()) %>%
      mutate(class_type = paste("Class", class_type))  # Label for readability

    fig <- plot_ly(class_legs, x = ~legs, y = ~count, color = ~class_type, type = "bar") %>%
      layout(title = "Leg Count Distribution by Animal Class",
             xaxis = list(title = "Number of Legs"),
             yaxis = list(title = "Animal Count"),
             barmode = "stack")
    
    fig
  })


  # 2. Donut Chart: Airborne Distribution
  output$airborne_donut <- renderPlotly({
    airborne_dist <- zoo_data %>%
      group_by(airborne) %>%
      summarise(count = n()) %>%
      mutate(airborne = factor(airborne, labels = c("Non-Airborne", "Airborne")))

    fig <- plot_ly(airborne_dist, labels = ~airborne, values = ~count, type = 'pie', hole = 0.4) %>%
      layout(title = "Distribution of Airborne Animals")
    
    fig
  })





  # 5. Area Chart: Predator Count by Class Type
  output$predator_area <- renderPlotly({
    predator_class <- zoo_data %>%
      filter(predator == 1) %>%
      group_by(class_type) %>%
      summarise(count = n()) %>%
      mutate(class_type = paste("Class", class_type))  # Adjusted for display issues

    fig <- plot_ly(predator_class, x = ~class_type, y = ~count, type = 'scatter', mode = 'lines+markers', fill = 'tozeroy') %>%
      layout(title = "Predator Count by Class Type")
    
    fig
  })

  # 6. Bar Chart: Leg Count Distribution
  output$legs_bar <- renderPlotly({
    leg_dist <- zoo_data %>%
      group_by(legs) %>%
      summarise(count = n())

    fig <- plot_ly(leg_dist, x = ~legs, y = ~count, type = "bar") %>%
      layout(title = "Distribution of Animals by Number of Legs")
    
    fig
  })


    # 1. Heatmap: Class Type by Leg Count
  output$class_legs_heatmap <- renderPlotly({
    class_legs <- zoo_data %>%
      group_by(class_type, legs) %>%
      summarise(count = n()) %>%
      mutate(class_type = paste("Class", class_type))  # Label for readability

    fig <- plot_ly(class_legs, x = ~legs, y = ~class_type, z = ~count, type = "heatmap", colors = "Blues") %>%
      layout(title = "Heatmap of Class Type by Leg Count")
    
    fig
  })

    # 4. Pie Chart: Animal Count by Class Type
  output$class_type_pie <- renderPlotly({
    class_dist <- zoo_data %>%
      group_by(class_type) %>%
      summarise(count = n()) %>%
      mutate(class_type = paste("Class", class_type))  # Adjusted for display issues

    fig <- plot_ly(class_dist, labels = ~class_type, values = ~count, type = 'pie') %>%
      layout(title = "Distribution of Animal Count by Class Type")
    
    fig
  })

}

# Run the application 
shinyApp(ui = ui, server = server)

Loading required package: shiny

Warning message:
"package 'shiny' was built under R version 4.4.2"
Loading required package: plotly

Warning message:
"package 'plotly' was built under R version 4.4.2"
Loading required package: ggplot2


Attaching package: 'plotly'


The following object is masked from 'package:ggplot2':

    last_plot


The following object is masked from 'package:stats':

    filter


The following object is masked from 'package:graphics':

    layout


Loading required package: dplyr


Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union



Listening on http://127.0.0.1:7197

`summarise()` has grouped output by 'class_type'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'class_type'. You can override using the
`.groups` argument.